--- #YAML:1.0
name:               WWW-NicoSound-Download
version:            1.02
abstract:           Get mp3 file from NicoSound web service
author:
    - Kuniyoshi Kouji <kuniyoshi@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Assert:  0
    HTML::DOM:     0.026
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
