--- #YAML:1.0
name:                WWW-NicoSound-Download
version:             1.07
abstract:            Get mp3 file from NicoSound web service
license:             perl
author:              
    - Kuniyoshi Kouji <kuniyoshi@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp::Assert:                  0
    Exception::Class:              0
    HTML::DOM:                     0.034
    Test::Exception:               0
    Test::File:                    0
    Test::More:                    0.94
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
